extends: stylelint-config-standard-scss
rules:
  # Consider the following as TODO
  alpha-value-notation: null
  at-rule-empty-line-before: null
  block-closing-brace-empty-line-before: null
  block-opening-brace-space-before: null
  color-function-notation: null
  color-hex-case: null
  comment-empty-line-before: null
  declaration-block-no-duplicate-properties: null
  declaration-block-no-redundant-longhand-properties: null
  declaration-block-semicolon-newline-after: null
  declaration-block-single-line-max-declarations: null
  declaration-block-trailing-semicolon: null
  declaration-empty-line-before: null
  function-comma-space-after: null
  indentation: null
  length-zero-no-unit: null
  max-empty-lines: null
  max-line-length: null
  no-descending-specificity: null
  no-duplicate-selectors: null
  no-invalid-position-at-import-rule: null
  number-leading-zero: null
  property-no-unknown: null
  rule-empty-line-before: null
  selector-attribute-quotes: null
  selector-class-pattern: null
  selector-id-pattern: null
  selector-list-comma-newline-after: null
  shorthand-property-no-redundant-values: null
  string-quotes: null
  scss/dollar-variable-empty-line-before: null
  scss/dollar-variable-pattern: null
  scss/double-slash-comment-empty-line-before: null
  scss/no-global-function-names: null
  scss/operator-no-unspaced: null
